services:
  caddy:
    image: caddy:2.7
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${APP_DOMAIN}
      - ACME_EMAIL=${ACME_EMAIL}
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - laravel.test

volumes:
  caddy_data:
  caddy_config:
